### ISSUE TITLE
Dagger does not generate class for TestComponent

### ISSUE THREAD

**Issue by dustin-graham** [chiuki/android-test-demo#1]
I'm trying to run your project in Android studio bug I'm finding a problem. Dagger does not seem to generate the Dagger class for the TestComponent defined in ActivityLauncher. I found the same issue in my own code and I'd like to know if there is anything else I'm supposed to do. ActivityLauncher line 34 shows an error where DaggerActivityLauncher_TestComponent is not found.

```
DemoApplication app
        = (DemoApplication) fetchInstrumentation().getTargetContext().getApplicationContext();
    TestComponent component = DaggerActivityLauncher_TestComponent.builder()
        .mockClockModule(new MockClockModule())
        .build();
    app.setComponent(component);
```

Thanks!

**Comment by chiuki** [comment]
`DaggerActivityLauncher_TestComponent` does not get generated until you build the test.

To build the test, open `MainActivityTest.java`, right click on `public class MainActivityTest`, and choose Run -> MainActivityTest (the one with the Android icon).

![run_test](https://cloud.githubusercontent.com/assets/354458/7266902/195e67ba-e86f-11e4-87da-029241bed3d8.png)

**Comment by dustin-graham** [comment]
Thanks! I guess I had thought this would have happened automatically. I did as you instructed and it does indeed work! Thank you so much!

**Comment by GaborPeto** [comment]
@chiuki Thank you very much! I've been going crazy with this for the last couple of hours. I thought my DI setup was missing something, turns out I just had to do what you suggested.

**Comment by lawloretienne** [comment]
I'm also having this issue, Dagger is not generating my TestComponent similar to what you have here
https://github.com/chiuki/android-test-demo/blob/624cfbb7b8ca5519fd8fe42649a5148cf4c3c850/app/src/androidTest/java/com/sqisland/android/test_demo/MockDemoApplication.java#L6

**Comment by XandrMaster** [comment]
> `DaggerActivityLauncher_TestComponent` does not get generated until you build the test.
> 
> To build the test, open `MainActivityTest.java`, right click on `public class MainActivityTest`, and choose Run -> MainActivityTest (the one with the Android icon).
> 
> ![run_test](https://cloud.githubusercontent.com/assets/354458/7266902/195e67ba-e86f-11e4-87da-029241bed3d8.png)

I spent time a lot for understand that . 
Thank you so much for help !

**Comment by EhtishamShami** [comment]
Hi chiuki solution works.
Basically in my point what it do, it run assembleAndroidTest gradle script. Which will generate the DaggerTestApplicationComponent for you.
Cheers
