### ISSUE TITLE
Is it okay to expose the components?

### ISSUE THREAD

**Issue by mheras** [chiuki/android-test-demo#2]
The `DemoApplication` exposes a `setComponent` method to the outside world. I understand you need to do that in order to make your tests set the test component to provide mocks, but anyone can call that method and break your app.

I think that `DemoApplication` and `MainActivity` should get their components somehow by not exposing their internals to the outside world, as that would violate the hiding principle.

Or am I missing something else?

Anyway, thanks for your demo! :)

**Comment by chiuki** [comment]
I don't like it either, but I can't think of a way to allow mocking without exposing `setComponent`. Suggestions welcome!

**Comment by mheras** [comment]
This is because of Dagger 2 design. Take a look at [this thread](https://github.com/google/dagger/issues/110). We are not alone. And I frankly can't use a dependency injection framework that makes me expose everything.

Another thing I don't like is that for `Activity` implementations, you have to leave your injected fields with package-level access, as Android instantiates them for us. This is an issue that Dagger can't solve, but it's still something I don't like.
