### ISSUE TITLE
Syntax error after import

### ISSUE THREAD

**Issue by vogella** [chiuki/android-test-demo#3]
If I import your project into Android Studio DaggerMainActivityTest_TestComponent cannot be resolved.

TestComponent component = DaggerMainActivityTest_TestComponent.builder()
        .mockClockModule(new MockClockModule())
        .build();

**Comment by chiuki** [comment]
Does it work after you build the test? See #1 for more information.

**Comment by vogella** [comment]
Thanks @chiuki works fine after retriggering the test build. Sorry for the noice.
