### ISSUE TITLE
Component duplication per test

### ISSUE THREAD

**Issue by chris-horner** [chiuki/android-test-demo#4]
Not sure this is really an issue, but I found it to be interesting.

It seems that when executing the tests, `DemoApplication`'s `onCreate()` method is called before `setComponent()`, so both the normal component and the test components are initialised before every test. (The `if component == null` check in `onCreate()` will always be true).

Is this a problem? Or we don't really care, just so long as it's called before an `Activity`'s `onCreate()`?

**Comment by chiuki** [comment]
It shouldn't be a problem, as long as `setComponent` for test is called before `inject` in the `Activity`.
